force-app/main/default/objects/Contact/fields/NotifyExternalSystem__c.field-meta.xml
<CustomField>
    <fullName>NotifyExternalSystem__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Used for NotifyExternalSystemBatchJob. if it is true, the internal system needs to notify external system about the attendee.</description>
    <label>NotifyExternalSystem</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SendEmail__c.field-meta.xml
<CustomField>
    <fullName>SendEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Used in SendEmailBatchJob to notify attendees about the reservation.</description>
    <label>SendEmail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Utils/HttpUtils/HttpUtils.cls
public class HttpUtils {
  public static void notifyExternalSystem(List<Contact> contacts) {
    for (Contact contact : contacts) {
      registerContact(contact);
    }
  }
  private static void registerContact(Contact contact) {
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    request.setEndpoint('callout:Reservation_System_API');
    request.setMethod('POST');
    request.setHeader('Content-Type', 'application/json;charset=UTF-8');
    request.setBody('{"name":"' + contact.Name + '-' + contact.Email + '}');
    HttpResponse response = http.send(request);
    if (response.getStatusCode() != 201) {
      Log.error(
        'The status code returned was not expected: ' +
        response.getStatusCode() +
        ' ' +
        response.getStatus()
      );
    } else {
      contact.SendEmail__c = true;
      contact.NotifyExternalSystem__c = false;
    }
  }
}