force-app/main/default/objects/Contact/fields/NotifyExternalSystem__c.field-meta.xml
<CustomField>
    <fullName>NotifyExternalSystem__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Used for NotifyExternalSystemBatchJob. if it is true, the internal system needs to notify external system about the attendee.</description>
    <label>NotifyExternalSystem</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SendEmail__c.field-meta.xml
<CustomField>
    <fullName>SendEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Used in SendEmailBatchJob to notify attendees about the reservation.</description>
    <label>SendEmail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Utils/EmailUtils/EmailUtilsTest.cls
@isTest
private class EmailUtilsTest {
  @isTest
  public static void sendEmailsSingleMode() {
    //Given
    Contact contact = (Contact) TestDataFactory.createSObject(
      'Contact',
      new Map<String, Object>{
        'LastName' => 'Contact',
        'Email' => 'contact.salesforce@gmail.com',
        'NotifyExternalSystem__c' => false,
        'SendEmail__c' => true
      }
    );

    //When
    Test.startTest();
    EmailUtils.sendEmails(new List<Contact>{ contact });
    Integer invocations = Limits.getEmailInvocations();
    Test.stopTest();

    //Then
    System.assert(invocations == 1);
    System.assert(!contact.SendEmail__c);
  }

  @isTest
  public static void sendsEmailBulkMode() {
    //Given
    Contact contact1 = (Contact) TestDataFactory.createSObject(
      'Contact',
      new Map<String, Object>{
        'LastName' => 'Contact1',
        'Email' => 'contact1.salesforce@gmail.com',
        'NotifyExternalSystem__c' => false,
        'SendEmail__c' => true
      }
    );
    Contact contact2 = (Contact) TestDataFactory.createSObject(
      'Contact',
      new Map<String, Object>{
        'LastName' => 'Contact',
        'Email' => 'contact2.salesforce@gmail.com',
        'NotifyExternalSystem__c' => false,
        'SendEmail__c' => true
      }
    );
    Contact contact3 = (Contact) TestDataFactory.createSObject(
      'Contact',
      new Map<String, Object>{
        'LastName' => 'Contact',
        'Email' => 'contact3.salesforce@gmail.com',
        'NotifyExternalSystem__c' => false,
        'SendEmail__c' => true
      }
    );

    //When
    Test.startTest();
    EmailUtils.sendEmails(new List<Contact>{ contact1, contact2, contact3 });
    Integer invocations = Limits.getEmailInvocations();
    Test.stopTest();

    //Then
    System.assert(invocations == 1);
    System.assert(!contact1.SendEmail__c);
    System.assert(!contact2.SendEmail__c);
    System.assert(!contact3.SendEmail__c);
  }
}