force-app/main/default/objects/Contact/fields/NotifyExternalSystem__c.field-meta.xml
<CustomField>
    <fullName>NotifyExternalSystem__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Used for NotifyExternalSystemBatchJob. if it is true, the internal system needs to notify external system about the attendee.</description>
    <label>NotifyExternalSystem</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SendEmail__c.field-meta.xml
<CustomField>
    <fullName>SendEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Used in SendEmailBatchJob to notify attendees about the reservation.</description>
    <label>SendEmail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batches/SendEmailBatchJob/SendEmailBatchJob.cls
public class SendEmailBatchJob implements Database.Batchable<sObject> {
  public Database.QueryLocator start(Database.BatchableContext BC) {
    String soqlQuery = 'Select Name, Email From Contact Where SendEmail__c = true And NotifyExternalSystem__c = false';
    return Database.getQueryLocator(soqlQuery);
  }
  public void execute(Database.BatchableContext BC, List<Contact> contacts) {
    EmailService.sendEmails(contacts);
    update contacts;
  }
  public void finish(Database.BatchableContext BC) {
  }
}